build laptop:
  image: alpine
  script: 
  - echo "Buildinga laptop"
  - mkdir build
  - touch build/computer.txt
  - echo "Mainboard" >> build/computer.txt
  - cat build/computer.txt
  - echo "Keyboard" >> build/computer.txt
  - cat build/computer.txt