# staging environment
# a) create a staging deployment environmenton aws s2 = s3xyz-bucket-staging
# b) Add bucket name to gitlab env
stages:
  - build
  - test
  - deploy staging
  - test staging
  - deploy production
  - test production

variables:
  APP_BASE_URL: http;s3...
  APP_BASE_URL_STAGING: http:s3

build website:
  images: node:16-alpine
  stages: build
  script:
    - yarn install
    - yarn lint
    - yarn test
    - yarn build
  artifacts:
    paths:
      - build

test website:
  images: node:16-alpine
  stages: test
  scripts:
    - yarn global add serve
    - apk add curl
    - serve -s build &
    - sleep 10
    - curl http://localhost:3000 | grep "React App"     #grep download the page source

deploy to staging:
  images: 
    name: amazon/aws-cli:2.4.2
    entrypoint: [""]
  stage: deploy staging
  rules:
    - if: $CI_COMMIT_BRANCH_NAME == $CI_DEFAULT_BRANCH
  script:
    - aws --version
    - $CI_COMMIT_BRANCH_NAME    #for debugging purposes to see the gitlab variable, nothing serious
    - aws s3 sync build s3://$AWS_S3_BUCKET_STAGING --delete 

staging test:
  stage: test staging
  image: curlimage/curl    #you can search the images that have the script command you want to use
  rules:
    - if: $CI_COMMIT_BRANCH_NAME == $CI_DEFAULT_BRANCH    #using gitlab variable
  scripts:
    - curl $APP_BASE_URL_STAGING | grep "React App"

deploy to s3:
  stage: deploy production
  images: 
    name: amazon/aws-cli:2.4.2
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH_NAME == $CI_DEFAULT_BRANCH    #using gitlab variable
  scripts:
    - aws --version
    - $CI_COMMIT_BRANCH_NAME    #for debugging purposes to see the gitlab variable, nothing serious
    - aws s3 sync build s3://$AWS_S3_BUCKET --delete 
  
production test:
  stage: test production
  image: curlimage/curl    #you can search the images that have the script command you want to use
  rules:
    - if: $CI_COMMIT_BRANCH_NAME == $CI_DEFAULT_BRANCH    #using gitlab variable
  scripts:
    - curl $APP_BASE_URL | grep "React App"


# Create new environment in GITLAB Deployment (LSB); -production, - staging